# Generated by Django 5.2.18 on 2026-10-07 06:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan Canitas', max_length=100, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('410000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo trimestral')),
                ('months', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='duración en meses')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='descuento porcentual')),
                ('included_exams', models.JSONField(blank=True, default=dict, verbose_name='exámenes incluidos por tipo')),
                ('active', models.BooleanField(default=True, verbose_name='vigente para nuevas inscripciones')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('CONSULT', 'Consulta'), ('EXAM', 'Examen'), ('HOSPITAL', 'Hospitalización'), ('SPA', 'Spa'), ('PRODUCT', 'Producto'), ('PLAN', 'Plan Canitas')], max_length=10, verbose_name='tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo directo estimado')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='impuesto porcentual')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('VET', 'Veterinario'), ('RECEPTION', 'Recepcionista')], default='RECEPTION', max_length=12, verbose_name='rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField(verbose_name='inicio')),
                ('ends', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_PROGRESS', 'En curso'), ('ATTENDED', 'Atendida'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=15, verbose_name='estado')),
                ('reason', models.TextField(blank=True, verbose_name='motivo o notas')),
                ('vet', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'VET'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='veterinario')),
            ],
            options={
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='diagnóstico')),
                ('recommendations', models.TextField(verbose_name='recomendaciones')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clinic.appointment', verbose_name='cita')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('address', models.CharField(max_length=250, verbose_name='dirección')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{7,15}$', 'Ingresa entre 7 y 15 dígitos.')], verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='customer_email_ci')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateField(default=django.utils.timezone.localdate, verbose_name='inicio')),
                ('ends', models.DateField(verbose_name='fin')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('included_exams', models.JSONField(default=dict)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.customer', verbose_name='propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ingreso')),
                ('estimated_discharge', models.DateTimeField(blank=True, null=True, verbose_name='salida estimada')),
                ('discharged_at', models.DateTimeField(blank=True, null=True, verbose_name='alta')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('care', models.TextField(verbose_name='cuidados especiales')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo diario al cliente')),
                ('summary', models.TextField(blank=True, verbose_name='resumen de alta')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.consultation', verbose_name='consulta')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service', verbose_name='tarifa de hospitalización')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='observación médica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='clinic.hospitalization', verbose_name='hospitalización')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Pago parcial'), ('PAID', 'Pagada')], default='PENDING', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.consultation')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.enrollment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='frecuencia')),
                ('duration', models.CharField(max_length=100, verbose_name='duración')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='clinic.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tendered', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('change', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia')], max_length=12)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinic.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('species', models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], max_length=4, verbose_name='especie')),
                ('breed', models.CharField(max_length=100, verbose_name='raza')),
                ('birth_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='peso en kg')),
                ('notes', models.TextField(blank=True, verbose_name='alergias e historia inicial')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.customer', verbose_name='propietario')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.pet'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pets',
            field=models.ManyToManyField(to='clinic.pet', verbose_name='mascotas'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.pet', verbose_name='mascota'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.planconfig', verbose_name='configuración'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_kind', models.CharField(blank=True, max_length=12)),
                ('included', models.BooleanField(default=False)),
                ('benefit_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.enrollment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clinic.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BLOOD', 'Sangre'), ('URINE', 'Orina'), ('ULTRASOUND', 'Ecografía'), ('XRAY', 'Radiografía')], max_length=12, verbose_name='tipo')),
                ('results', models.TextField(blank=True, verbose_name='resultado o borrador')),
                ('attachment', models.FileField(blank=True, upload_to='exams/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='archivo PDF o imagen')),
                ('completed', models.BooleanField(default=False, verbose_name='resultado definitivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.consultation', verbose_name='consulta')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service', verbose_name='tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service', verbose_name='servicio'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField(verbose_name='inicio')),
                ('ends', models.DateTimeField(verbose_name='fin')),
                ('kind', models.CharField(choices=[('DAY', 'Día 08 a 20'), ('NIGHT', 'Noche 20 a 08')], max_length=5, verbose_name='turno')),
                ('vet', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'VET'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='veterinario')),
            ],
            options={
                'ordering': ['starts'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends__gt', models.F('starts'))), name='appointment_positive'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('ends__gt', models.F('starts'))), name='shift_positive'),
        ),
    ]
